# Generated by Django 5.2.5 on 2025-09-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruppoAutorizzativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtenteGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gruppoautorizzativo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.utente')),
            ],
        ),
    ]
