# Generated by Django 5.2.5 on 2025-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppoautorizzativo',
            options={'verbose_name': 'Gruppo Autorizzativo', 'verbose_name_plural': 'Gruppi Autorizzativi'},
        ),
        migrations.RenameIndex(
            model_name='menuvoce',
            new_name='accounts_me_attivo_b44514_idx',
            old_name='accounts_men_attivo_b8b9c4_idx',
        ),
        migrations.RenameIndex(
            model_name='menuvoce',
            new_name='accounts_me_id_padr_2d055c_idx',
            old_name='accounts_men_id_padr_f9d2a1_idx',
        ),
        migrations.AlterField(
            model_name='gruppoautorizzativo',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
